<?php

namespace Database\Seeders;

use App\Enums\ContentPageType;
use App\Enums\PageStatus;
use App\Enums\PromotionEligibilityScope;
use App\Enums\PromotionType;
use App\Enums\ReviewSource;
use App\Enums\Status;
use App\Enums\TyreCategory;
use App\Enums\TyreConstruction;
use App\Enums\TyreSidewall;
use App\Enums\TyreType;
use App\Enums\VehicleFitmentConfidence;
use App\Enums\VehicleFitmentPosition;
use App\Enums\VehicleFitmentSource;
use App\Models\Brand;
use App\Models\ContentPage;
use App\Models\Faq;
use App\Models\InventoryItem;
use App\Models\PopularSize;
use App\Models\Promotion;
use App\Models\Review;
use App\Models\ServiceZone;
use App\Models\State;
use App\Models\StockLocation;
use App\Models\Suburb;
use App\Models\Technician;
use App\Models\TechnicianShift;
use App\Models\TyreModel;
use App\Models\TyreVariant;
use App\Models\Van;
use App\Models\Vehicle;
use App\Models\VehicleFitment;
use Database\Seeders\Demo\DemoContent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * DEMO data for development and storefront design/QA, run on demand:
 * `php artisan db:seed --class=DemoCatalogSeeder`. Not part of
 * {@see DatabaseSeeder} and refuses to run in production.
 *
 * What it does, all idempotent (safe to re-run; rows are matched by slug/sku/
 * name, never duplicated, admin edits to existing rows are left alone):
 *  - a realistic catalogue: tiered brands (premium/mid/budget), 40+ patterns,
 *    12 popular AU sizes each with 3+ patterns per tier, stock at every depot;
 *  - demo depots, vans, technicians and 28 days of shifts so booking slots
 *    exist for every launch city, plus extra suburbs;
 *  - public offers (incl. auto-applied 4 for 3), vehicles with fitments,
 *    reviews, blog posts, guides, FAQs.
 *
 * Junk left behind by the faker/e2e suites (brands, zones, depots, offers,
 * vehicles, reviews, content named "E2E ...", "QA ..." or generated by the
 * factories) is HIDDEN, not deleted: status set to inactive/archived or
 * is_hidden set. Nothing is removed, so it is reversible from the admin
 * panel. Run `php artisan db:seed --class=DemoCatalogSeeder` again after an
 * e2e run to re-hide new junk.
 *
 * All prices, copy and review text are invented placeholders.
 */
class DemoCatalogSeeder extends Seeder
{
    use WithoutModelEvents;

    /** Brand => [country, tier]. */
    private const BRANDS = [
        'Michelin' => ['France', 'premium'],
        'Bridgestone' => ['Japan', 'premium'],
        'Goodyear' => ['USA', 'premium'],
        'Continental' => ['Germany', 'premium'],
        'Pirelli' => ['Italy', 'premium'],
        'Hankook' => ['South Korea', 'mid'],
        'Yokohama' => ['Japan', 'mid'],
        'Toyo' => ['Japan', 'mid'],
        'Kumho' => ['South Korea', 'mid'],
        'Westlake' => ['China', 'budget'],
        'Achilles' => ['Indonesia', 'budget'],
        'Linglong' => ['China', 'budget'],
        'Sailun' => ['China', 'budget'],
        'Nankang' => ['Taiwan', 'budget'],
    ];

    /**
     * Model key "Brand|Name" => [category, type, run_flat, price factor, months since release].
     *
     * @var array<string, array{0: string, 1: string, 2: bool, 3: float, 4: int}>
     */
    private const MODELS = [
        // Passenger / standard.
        'Michelin|Primacy 4' => ['car', 'highway', false, 1.06, 8],
        'Bridgestone|Turanza T005' => ['car', 'highway', false, 1.00, 10],
        'Goodyear|EfficientGrip Performance 2' => ['car', 'eco', false, 0.98, 14],
        'Continental|PremiumContact 6' => ['car', 'highway', false, 1.04, 20],
        'Hankook|Kinergy Eco 2' => ['car', 'eco', false, 1.00, 30],
        'Yokohama|BluEarth-GT AE51' => ['car', 'eco', false, 1.04, 18],
        'Toyo|Proxes Comfort' => ['car', 'highway', false, 1.02, 12],
        'Kumho|Solus TA31' => ['car', 'highway', false, 0.96, 26],
        'Westlake|RP28' => ['car', 'highway', false, 0.95, 40],
        'Achilles|122' => ['car', 'highway', false, 1.00, 36],
        'Linglong|Green-Max' => ['car', 'eco', false, 1.04, 22],
        // Performance.
        'Michelin|Pilot Sport 4' => ['car', 'performance', false, 1.08, 30],
        'Continental|MaxContact MC6' => ['car', 'performance', false, 1.04, 9],
        'Pirelli|P Zero' => ['car', 'performance', false, 1.10, 15],
        'Hankook|Ventus S1 evo3' => ['car', 'performance', false, 1.00, 16],
        'Kumho|Ecsta PS71' => ['car', 'performance', false, 0.96, 28],
        'Sailun|Atrezzo ZSR2' => ['car', 'performance', false, 1.00, 6],
        'Nankang|NS-25' => ['car', 'performance', false, 0.96, 24],
        // Run-flat.
        'Bridgestone|Turanza T005 RunFlat' => ['car', 'highway', true, 1.30, 11],
        'Continental|ContiSportContact 5 SSR' => ['car', 'performance', true, 1.34, 34],
        // SUV.
        'Michelin|Latitude Sport 3' => ['suv', 'highway', false, 1.08, 40],
        'Bridgestone|Dueler H/P Sport' => ['suv', 'highway', false, 1.02, 33],
        'Continental|CrossContact LX Sport' => ['suv', 'highway', false, 1.04, 21],
        'Goodyear|Eagle F1 Asymmetric SUV' => ['suv', 'performance', false, 1.08, 13],
        'Hankook|Dynapro HP2' => ['suv', 'highway', false, 0.98, 27],
        'Yokohama|Geolandar CV G058' => ['suv', 'highway', false, 1.02, 25],
        'Kumho|Crugen HP71' => ['suv', 'highway', false, 0.98, 19],
        'Toyo|Proxes CF2 SUV' => ['suv', 'highway', false, 1.00, 29],
        'Westlake|SU318' => ['suv', 'highway', false, 0.94, 38],
        'Linglong|Crosswind HP010' => ['suv', 'highway', false, 1.00, 23],
        'Sailun|Terramax HLT' => ['suv', 'highway', false, 1.00, 17],
        // 4x4 / light truck.
        'Bridgestone|Dueler A/T 001' => ['4x4', 'all_terrain', false, 1.00, 18],
        'Goodyear|Wrangler Territory AT' => ['4x4', 'all_terrain', false, 1.00, 9],
        'Michelin|LTX Trail' => ['4x4', 'highway', false, 1.12, 14],
        'Continental|CrossContact ATR' => ['4x4', 'all_terrain', false, 1.02, 31],
        'Yokohama|Geolandar A/T G015' => ['4x4', 'all_terrain', false, 1.06, 22],
        'Kumho|Road Venture AT51' => ['4x4', 'all_terrain', false, 0.96, 20],
        'Toyo|Open Country A/T III' => ['4x4', 'all_terrain', false, 1.08, 12],
        'Hankook|Dynapro AT2' => ['4x4', 'all_terrain', false, 1.00, 24],
        'Westlake|SL369' => ['4x4', 'all_terrain', false, 0.94, 35],
        'Achilles|Desert Hawk X-MT' => ['4x4', 'mud_terrain', false, 1.06, 28],
        'Sailun|Terramax CVR' => ['4x4', 'all_terrain', false, 0.98, 10],
        'Nankang|FT-9' => ['4x4', 'mud_terrain', false, 1.02, 32],
    ];

    /** Model groups used to decide which models are stocked in a size. */
    private const GROUP_CAR = [
        'Michelin|Primacy 4', 'Bridgestone|Turanza T005', 'Goodyear|EfficientGrip Performance 2', 'Continental|PremiumContact 6',
        'Hankook|Kinergy Eco 2', 'Yokohama|BluEarth-GT AE51', 'Toyo|Proxes Comfort', 'Kumho|Solus TA31',
        'Westlake|RP28', 'Achilles|122', 'Linglong|Green-Max',
    ];

    private const GROUP_PERFORMANCE = [
        'Michelin|Pilot Sport 4', 'Continental|MaxContact MC6', 'Pirelli|P Zero',
        'Hankook|Ventus S1 evo3', 'Kumho|Ecsta PS71', 'Sailun|Atrezzo ZSR2', 'Nankang|NS-25',
    ];

    private const GROUP_RUNFLAT = ['Bridgestone|Turanza T005 RunFlat', 'Continental|ContiSportContact 5 SSR'];

    private const GROUP_SUV = [
        'Michelin|Latitude Sport 3', 'Bridgestone|Dueler H/P Sport', 'Continental|CrossContact LX Sport', 'Goodyear|Eagle F1 Asymmetric SUV',
        'Hankook|Dynapro HP2', 'Yokohama|Geolandar CV G058', 'Kumho|Crugen HP71', 'Toyo|Proxes CF2 SUV',
        'Westlake|SU318', 'Linglong|Crosswind HP010', 'Sailun|Terramax HLT',
    ];

    private const GROUP_4X4 = [
        'Bridgestone|Dueler A/T 001', 'Goodyear|Wrangler Territory AT', 'Michelin|LTX Trail', 'Continental|CrossContact ATR',
        'Yokohama|Geolandar A/T G015', 'Kumho|Road Venture AT51', 'Toyo|Open Country A/T III', 'Hankook|Dynapro AT2',
        'Westlake|SL369', 'Achilles|Desert Hawk X-MT', 'Sailun|Terramax CVR', 'Nankang|FT-9',
    ];

    /**
     * Size => [load index, speed rating, base premium price in dollars, groups].
     *
     * @var array<string, array{0: int, 1: string, 2: int, 3: list<list<string>>}>
     */
    private const SIZES = [
        '195/65R15' => [91, 'H', 165, [self::GROUP_CAR]],
        '205/55R16' => [91, 'V', 190, [self::GROUP_CAR, self::GROUP_RUNFLAT]],
        '205/65R16' => [95, 'H', 200, [self::GROUP_CAR]],
        '215/60R16' => [95, 'V', 205, [self::GROUP_CAR]],
        '215/55R17' => [94, 'V', 225, [self::GROUP_CAR, self::GROUP_PERFORMANCE]],
        '225/45R17' => [91, 'W', 235, [self::GROUP_CAR, self::GROUP_PERFORMANCE, self::GROUP_RUNFLAT]],
        '225/65R17' => [102, 'H', 245, [self::GROUP_SUV]],
        '205/65R18' => [99, 'H', 255, [self::GROUP_SUV]],
        '235/60R18' => [103, 'V', 275, [self::GROUP_SUV]],
        '245/45R18' => [100, 'W', 285, [self::GROUP_CAR, self::GROUP_PERFORMANCE, self::GROUP_RUNFLAT]],
        '265/65R17' => [112, 'T', 290, [self::GROUP_4X4, self::GROUP_SUV]],
        '265/70R16' => [112, 'S', 275, [self::GROUP_4X4]],
    ];

    private const TIER_FACTOR = ['premium' => 1.0, 'mid' => 0.79, 'budget' => 0.62];

    /** Demo depot name => [address, lat, lng]. */
    private const DEMO_DEPOTS = [
        'Brisbane Depot' => ['1 Example Road, Brisbane QLD 4000', -27.4698, 153.0251],
        'Perth Depot' => ['1 Example Road, Perth WA 6000', -31.9505, 115.8605],
        'Adelaide Depot' => ['1 Example Road, Adelaide SA 5000', -34.9285, 138.6007],
    ];

    public function run(): void
    {
        if (app()->isProduction()) {
            throw new RuntimeException('DemoCatalogSeeder refuses to run in production.');
        }

        DB::transaction(function (): void {
            $this->hideJunk();
        });

        $this->call(LaunchCitiesSeeder::class);

        $brands = $this->seedBrands();
        $this->seedCatalogue($brands);
        $this->seedLocationsAndOperations();
        $this->seedVehicles();
        $this->seedOffers();
        $this->seedContent();
        $this->seedReviews();

        $this->command?->info('Demo catalogue seeded: '.TyreVariant::query()->where('status', Status::Active)->count().' active variants across '
            .Brand::query()->where('status', Status::Active)->count().' brands.');
    }

    /**
     * Hide faker/e2e leftovers (never delete).
     */
    private function hideJunk(): void
    {
        $keepBrands = array_keys(self::BRANDS);
        Brand::query()->where('status', Status::Active)->whereNotIn('name', $keepBrands)->update(['status' => Status::Inactive]);

        $hiddenBrandIds = Brand::query()->where('status', '!=', Status::Active)->pluck('id');
        TyreModel::query()->whereIn('brand_id', $hiddenBrandIds)->where('status', Status::Active)->update(['status' => Status::Inactive]);

        $keepZones = [
            'Melbourne Metro', 'Melbourne CBD Express', 'Geelong & Surrounds', 'Sydney Inner West',
            'Brisbane Metro', 'Gold Coast', 'Perth Metro', 'Adelaide Metro',
        ];
        ServiceZone::query()->where('status', Status::Active)->whereNotIn('name', $keepZones)->update(['status' => Status::Inactive]);

        Promotion::query()->where('status', Status::Active)->where('name', 'like', 'E2E%')->update(['status' => Status::Inactive]);

        Vehicle::query()->where('status', Status::Active)->where('make', 'like', 'E2E%')->update(['status' => Status::Inactive]);

        Review::query()->where(function ($query): void {
            $query->where('author_name', 'like', 'E2E%')->orWhere('body', 'like', 'E2E%');
        })->update(['is_hidden' => true]);

        ContentPage::query()->where('status', '!=', PageStatus::Archived)
            ->where(function ($query): void {
                $query->where('title', 'like', 'E2E%')->orWhere('slug', 'like', 'e2e-%')->orWhere('slug', 'draft-post');
            })
            ->update(['status' => PageStatus::Archived]);

        Faq::query()->where('status', '!=', PageStatus::Archived)
            ->where(function ($query): void {
                $query->where('question', 'like', 'E2E%')->orWhere('question', 'Draft FAQ');
            })
            ->update(['status' => PageStatus::Archived]);
    }

    /**
     * @return array<string, Brand>
     */
    private function seedBrands(): array
    {
        $brands = [];

        foreach (self::BRANDS as $name => [$country, $tier]) {
            $brand = Brand::query()->firstOrCreate(
                ['slug' => Str::slug($name)],
                ['name' => $name, 'logo_path' => null, 'country_of_origin' => $country, 'tier' => $tier, 'status' => Status::Active],
            );

            $changes = [];

            if ($brand->tier === null) {
                $changes['tier'] = $tier;
            }

            if ($brand->status !== Status::Active) {
                $changes['status'] = Status::Active;
            }

            if ($changes !== []) {
                $brand->update($changes);
            }

            $brands[$name] = $brand;
        }

        return $brands;
    }

    /**
     * @param  array<string, Brand>  $brands
     */
    private function seedCatalogue(array $brands): void
    {
        $stockLocationIds = $this->ensureDepots();
        $models = [];

        foreach (self::SIZES as $size => [$load, $speed, $basePremium, $groups]) {
            [$width, $profile, $rim] = array_map('intval', preg_split('/[\/R]/', $size));

            foreach (collect($groups)->flatten()->unique() as $modelKey) {
                [$brandName, $modelName] = explode('|', $modelKey);
                [$category, $type, $runFlat, $factor, $monthsAgo] = self::MODELS[$modelKey];

                $model = $models[$modelKey] ??= $this->ensureModel($brands[$brandName], $modelName, $category, $type, $runFlat, $monthsAgo);

                $tier = self::BRANDS[$brandName][1];
                $dollars = $basePremium * self::TIER_FACTOR[$tier] * $factor;

                if ($category === 'car' && $type === 'performance') {
                    $dollars *= 1.06;
                }

                $price = (int) (round($dollars / 10) * 10 - 1) * 100;
                $modelSpeed = $type === 'performance' && $rim >= 17 ? $this->speedUp($speed) : $speed;
                $modelLoad = $load + ($type === 'performance' ? 1 : 0) + ($tier === 'budget' ? 0 : (crc32($modelKey) % 2));

                $this->ensureVariant($model, $width, $profile, $rim, (string) $modelLoad, $modelSpeed, $price, $runFlat ? TyreSidewall::Reinforced : TyreSidewall::Standard, $stockLocationIds);
            }
        }

        $popular = ['205/55R16', '225/45R17', '235/60R18', '215/60R16', '265/65R17', '195/65R15', '225/65R17', '205/65R16'];

        foreach ($popular as $order => $size) {
            [$width, $profile, $rim] = array_map('intval', preg_split('/[\/R]/', $size));
            PopularSize::query()->firstOrCreate(
                ['width' => $width, 'profile' => $profile, 'rim_diameter' => $rim],
                ['sort_order' => $order + 1, 'status' => Status::Active],
            );
        }
    }

    private function speedUp(string $speed): string
    {
        return ['H' => 'V', 'V' => 'W', 'W' => 'Y', 'T' => 'H', 'S' => 'T'][$speed] ?? $speed;
    }

    /**
     * @return list<int>
     */
    private function ensureDepots(): array
    {
        $ids = StockLocation::query()->whereIn('name', ['Melbourne Depot', 'Sydney Depot'])->pluck('id')->all();

        foreach (self::DEMO_DEPOTS as $name => [$address, $lat, $lng]) {
            $ids[] = StockLocation::query()->firstOrCreate(['name' => $name], ['address' => $address, 'lat' => $lat, 'lng' => $lng])->id;
        }

        return $ids;
    }

    private function ensureModel(Brand $brand, string $name, string $category, string $type, bool $runFlat, int $monthsAgo): TyreModel
    {
        $model = TyreModel::query()->firstOrCreate(
            ['slug' => Str::slug($brand->name.' '.$name)],
            [
                'brand_id' => $brand->id,
                'name' => $name,
                'category' => TyreCategory::from($category),
                'tyre_type' => TyreType::from($type),
                'construction' => TyreConstruction::Radial,
                'run_flat' => $runFlat,
                'description' => $this->describe($brand->name, $name, $type, $runFlat),
                'warranty_text' => 'Manufacturer warranty against defects in materials and workmanship applies. See warranty terms for full conditions.',
                'warranty_km' => ['premium' => 80000, 'mid' => 60000, 'budget' => 40000][$brand->tier?->value ?? 'mid'],
                'service_inclusions' => ['Onsite fitting', 'Computer wheel balancing', 'New valves', 'Recycling of old tyres'],
                'released_at' => Carbon::now()->subMonths($monthsAgo)->toDateString(),
                'images' => [],
                'status' => Status::Active,
            ],
        );

        if ($model->status !== Status::Active) {
            $model->update(['status' => Status::Active]);
        }

        return $model;
    }

    private function describe(string $brand, string $name, string $type, bool $runFlat): string
    {
        $focus = [
            'highway' => 'a quiet, comfortable everyday tyre with confident wet braking',
            'eco' => 'a fuel-saving tyre with low rolling resistance and long tread life',
            'performance' => 'a high-grip tyre with sharp steering response for spirited driving',
            'all_terrain' => 'a rugged all-terrain tyre that balances sealed-road manners with gravel and dirt traction',
            'mud_terrain' => 'an aggressive mud-terrain tyre built for serious off-road work',
        ][$type];

        return "The {$brand} {$name} is {$focus}.".($runFlat ? ' Run-flat construction lets you keep driving a limited distance after a puncture.' : '');
    }

    /**
     * @param  list<int>  $stockLocationIds
     */
    private function ensureVariant(TyreModel $model, int $width, int $profile, int $rim, string $load, string $speed, int $price, TyreSidewall $sidewall, array $stockLocationIds): void
    {
        $existing = TyreVariant::query()
            ->where('tyre_model_id', $model->id)
            ->where('width', $width)->where('profile', $profile)->where('rim_diameter', $rim)
            ->first();

        if ($existing === null) {
            $unsaved = new TyreVariant(['tyre_model_id' => $model->id, 'width' => $width, 'profile' => $profile, 'rim_diameter' => $rim, 'load_index' => $load, 'speed_rating' => $speed]);
            $unsaved->setRelation('tyreModel', $model);

            $existing = TyreVariant::query()->create([
                'tyre_model_id' => $model->id,
                'sku' => Str::upper(Str::slug($model->slug, '')).'-'.$width.$profile.$rim,
                'slug' => TyreVariant::generateUniqueSlug($unsaved),
                'width' => $width,
                'profile' => $profile,
                'rim_diameter' => $rim,
                'load_index' => $load,
                'speed_rating' => $speed,
                'sidewall' => $sidewall,
                'ean' => null,
                'weight_kg' => round(7 + $width * $profile / 100 / 100 * 1.2 + $rim * 0.35, 1),
                'base_price' => $price,
                'status' => Status::Active,
            ]);
        } elseif ($existing->status !== Status::Active) {
            $existing->update(['status' => Status::Active]);
        }

        foreach ($stockLocationIds as $stockLocationId) {
            $seed = crc32($existing->sku.$stockLocationId);

            InventoryItem::query()->firstOrCreate(
                ['tyre_variant_id' => $existing->id, 'stock_location_id' => $stockLocationId],
                ['qty_on_hand' => $seed % 19 === 0 ? 2 : 8 + ($seed % 33), 'qty_reserved' => 0, 'reorder_point' => 3],
            );
        }
    }

    /**
     * Extra suburbs, depots linkage, vans, technicians and shifts for the next 28 days.
     */
    private function seedLocationsAndOperations(): void
    {
        $this->seedSuburbs();

        $depotByZone = [
            'Melbourne Metro' => 'Melbourne Depot', 'Melbourne CBD Express' => 'Melbourne Depot', 'Geelong & Surrounds' => 'Melbourne Depot',
            'Sydney Inner West' => 'Sydney Depot', 'Brisbane Metro' => 'Brisbane Depot', 'Gold Coast' => 'Brisbane Depot',
            'Perth Metro' => 'Perth Depot', 'Adelaide Metro' => 'Adelaide Depot',
        ];

        foreach ($depotByZone as $zoneName => $depotName) {
            $zone = ServiceZone::query()->where('name', $zoneName)->first();
            $depot = StockLocation::query()->where('name', $depotName)->first();

            if ($zone === null || $depot === null) {
                continue;
            }

            $depot->serviceZones()->syncWithoutDetaching([$zone->id]);
            $this->seedTeam($zone, $depot);
        }
    }

    private function seedSuburbs(): void
    {
        $vic = State::query()->where('code', 'VIC')->first();
        $nsw = State::query()->where('code', 'NSW')->first();

        foreach ([
            ['Carlton', '3053', -37.8002, 144.9669], ['Fitzroy', '3065', -37.7989, 144.9784], ['South Yarra', '3141', -37.8397, 144.9930],
            ['Brunswick', '3056', -37.7667, 144.9605], ['Footscray', '3011', -37.8000, 144.8996], ['Hawthorn', '3122', -37.8226, 145.0353],
        ] as [$name, $postcode, $lat, $lng]) {
            Suburb::query()->firstOrCreate(['name' => $name, 'state_id' => $vic->id, 'postcode' => $postcode], ['lat' => $lat, 'lng' => $lng]);
        }

        foreach ([['Geelong West', '3218', -38.1411, 144.3446], ['Belmont', '3216', -38.1778, 144.3524]] as [$name, $postcode, $lat, $lng]) {
            Suburb::query()->firstOrCreate(['name' => $name, 'state_id' => $vic->id, 'postcode' => $postcode], ['lat' => $lat, 'lng' => $lng]);
        }

        $innerWest = ServiceZone::query()->where('name', 'Sydney Inner West')->first();
        $attach = [];

        foreach ([
            ['Leichhardt', '2040', -33.8832, 151.1566], ['Balmain', '2041', -33.8588, 151.1790], ['Glebe', '2037', -33.8795, 151.1856],
            ['Ashfield', '2131', -33.8886, 151.1252], ['Burwood', '2134', -33.8774, 151.1040],
        ] as [$name, $postcode, $lat, $lng]) {
            $attach[] = Suburb::query()->firstOrCreate(['name' => $name, 'state_id' => $nsw->id, 'postcode' => $postcode], ['lat' => $lat, 'lng' => $lng])->id;
        }

        $innerWest?->suburbs()->syncWithoutDetaching($attach);
    }

    /**
     * Two technicians and vans per zone, with weekday and Saturday shifts for 28 days.
     */
    private function seedTeam(ServiceZone $zone, StockLocation $depot): void
    {
        $code = Str::upper(Str::substr(Str::slug($zone->name, ''), 0, 6));
        $first = ['Alex', 'Jordan', 'Sam', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Jamie'];

        foreach ([1, 2] as $n) {
            $name = $first[crc32($zone->name.$n) % count($first)].' '.['Hughes', 'Nguyen', 'Patel', 'Walker', 'Rossi'][crc32($zone->name.$n.'x') % 5].' (demo)';
            $technician = Technician::query()->firstOrCreate(['name' => $name.' '.$code.$n], ['employment_type' => 'employee', 'certifications' => [], 'status' => Status::Active]);
            $van = Van::query()->firstOrCreate(
                ['rego' => 'DEMO'.$code.$n],
                ['name' => $zone->name.' Van '.$n, 'home_stock_location_id' => $depot->id, 'has_alignment_equipment' => $n === 1, 'max_jobs_per_day' => 6, 'status' => Status::Active],
            );

            for ($day = 1; $day <= 28; $day++) {
                $date = Carbon::today()->addDays($day);
                $hours = $zone->operating_hours[strtolower($date->format('D'))] ?? null;

                if ($hours === null) {
                    continue;
                }

                $isSaturday = $date->isSaturday();
                $start = $isSaturday ? max($hours['open'], '09:00') : max($hours['open'], '07:30');
                $end = $isSaturday ? min($hours['close'], '14:00') : min($hours['close'], '17:00');

                TechnicianShift::query()->firstOrCreate(
                    ['technician_id' => $technician->id, 'date' => $date->toDateString(), 'shift_start' => $start.':00'],
                    ['van_id' => $van->id, 'service_zone_id' => $zone->id, 'shift_end' => $end.':00', 'status' => Status::Active],
                );
            }
        }
    }

    private function seedVehicles(): void
    {
        $rows = [
            ['Toyota', 'Hilux', 'Workmate', 'ute', 2015, 2024, [[265, 65, 17, '112', 'S']]],
            ['Toyota', 'Hilux', 'SR5', 'ute', 2015, 2024, [[265, 60, 18, '110', 'H']]],
            ['Toyota', 'RAV4', 'GX', 'suv', 2019, 2024, [[225, 65, 17, '102', 'H']]],
            ['Toyota', 'Camry', 'Ascent', 'sedan', 2018, 2024, [[215, 55, 17, '94', 'V']]],
            ['Mazda', 'Mazda3', 'G20', 'hatch', 2014, 2019, [[205, 60, 16, '92', 'H']]],
            ['Hyundai', 'i30', 'Active', 'hatch', 2017, 2024, [[205, 55, 16, '91', 'V']]],
            ['Hyundai', 'Tucson', 'Elite', 'suv', 2021, 2024, [[235, 60, 18, '103', 'H']]],
            ['Kia', 'Cerato', 'S', 'sedan', 2018, 2024, [[205, 55, 16, '91', 'V']]],
            ['Mitsubishi', 'Triton', 'GLX', 'ute', 2015, 2024, [[265, 65, 17, '112', 'S']]],
            ['Isuzu', 'D-MAX', 'LS-U', 'ute', 2020, 2024, [[265, 65, 17, '112', 'S']]],
            ['Subaru', 'Forester', '2.5i', 'suv', 2018, 2024, [[225, 60, 17, '99', 'H']]],
            ['Volkswagen', 'Golf', '110TSI', 'hatch', 2017, 2023, [[225, 45, 17, '91', 'W']]],
            ['Honda', 'Civic', 'VTi', 'sedan', 2016, 2021, [[215, 55, 16, '93', 'V']]],
            ['Nissan', 'X-Trail', 'ST-L', 'suv', 2014, 2022, [[225, 65, 17, '102', 'H']]],
            ['BMW', '3 Series', '320i', 'sedan', 2019, 2024, [[225, 45, 17, '91', 'W']]],
            ['BMW', '3 Series', 'M340i', 'sedan', 2019, 2024, [[245, 45, 18, '100', 'W']]],
            ['Ford', 'Ranger', 'XLT', 'ute', 2011, 2018, [[265, 65, 17, '112', 'S']]],
            ['Mazda', 'CX-5', 'Maxx Sport', 'suv', 2017, 2024, [[225, 65, 17, '102', 'H']]],
        ];

        foreach ($rows as [$make, $model, $series, $body, $from, $to, $fitments]) {
            $vehicle = Vehicle::query()->where(['make' => $make, 'model' => $model, 'series' => $series, 'year_from' => $from, 'year_to' => $to])->first();

            if ($vehicle === null) {
                $unsaved = new Vehicle(['make' => $make, 'model' => $model, 'series' => $series, 'year_from' => $from, 'year_to' => $to]);
                $vehicle = Vehicle::query()->create([
                    'make' => $make, 'model' => $model, 'series' => $series, 'body_type' => $body,
                    'year_from' => $from, 'year_to' => $to, 'slug' => Vehicle::generateUniqueSlug($unsaved), 'status' => Status::Active,
                ]);
            }

            foreach ($vehicle->fitments()->exists() ? [] : $fitments as $index => [$width, $profile, $rim, $load, $speed]) {
                VehicleFitment::query()->create([
                    'vehicle_id' => $vehicle->id, 'position' => VehicleFitmentPosition::All,
                    'width' => $width, 'profile' => $profile, 'rim_diameter' => $rim, 'load_index' => $load, 'speed_rating' => $speed,
                    'is_staggered' => false, 'source' => VehicleFitmentSource::Manual,
                    'confidence' => $index === 0 ? VehicleFitmentConfidence::Confirmed : VehicleFitmentConfidence::Likely,
                    'status' => Status::Active,
                ]);
            }
        }
    }

    private function seedOffers(): void
    {
        $brand = fn (string $slug): ?Brand => Brand::query()->where('slug', $slug)->first();

        $offers = [
            [
                'slug' => 'goodyear-4-for-3', 'brandSlug' => 'goodyear', 'code' => null,
                'name' => 'Goodyear 4 for 3', 'title' => 'Buy 3 Goodyear tyres, get the 4th free',
                'summary' => 'Fit a full set of Goodyear tyres and the cheapest one is on us. Applied automatically.',
                'badge_text' => '4 for 3', 'discount_description' => 'Fourth tyre free', 'type' => PromotionType::FourForThree, 'value' => 0,
            ],
            [
                'slug' => 'hankook-4-for-3', 'brandSlug' => 'hankook', 'code' => null,
                'name' => 'Hankook 4 for 3', 'title' => 'Hankook 4 for 3',
                'summary' => 'Buy four Hankook tyres, pay for three.',
                'badge_text' => '4 for 3', 'discount_description' => 'Fourth tyre free', 'type' => PromotionType::FourForThree, 'value' => 0,
            ],
            [
                'slug' => 'bridgestone-4-for-3', 'brandSlug' => 'bridgestone', 'code' => 'BRIDGESTONE4',
                'name' => 'Bridgestone 4 for 3', 'title' => 'Buy 3 Bridgestone tyres, get the 4th free',
                'summary' => 'Buy four Bridgestone tyres, pay for three. Applied automatically.',
                'badge_text' => '4 for 3', 'discount_description' => 'Fourth tyre free', 'type' => PromotionType::FourForThree, 'value' => 0,
            ],
            [
                'slug' => 'michelin-20-off', 'brandSlug' => 'michelin', 'code' => 'MICHELIN20',
                'name' => 'Michelin $20 off each tyre', 'title' => '$20 off every Michelin tyre',
                'summary' => 'Save $20 on every Michelin tyre. Applied automatically.',
                'badge_text' => '$20 off', 'discount_description' => '$20 off each tyre', 'type' => PromotionType::Fixed, 'value' => 2000,
            ],
            [
                'slug' => 'welcome-10', 'brandSlug' => null, 'code' => 'WELCOME10',
                'name' => 'Welcome 10% off', 'title' => '10% off your first order',
                'summary' => 'New to Tiro? Enjoy 10% off your tyres, applied automatically.',
                'badge_text' => '10% off', 'discount_description' => '10% off tyres', 'type' => PromotionType::Percentage, 'value' => 10,
            ],
        ];

        foreach ($offers as $offer) {
            $promotion = Promotion::query()->where('slug', $offer['slug'])->first();

            if ($promotion !== null) {
                if ($promotion->status !== Status::Active || ! $promotion->is_public || $promotion->ends_at?->isPast()) {
                    $promotion->update(['status' => Status::Active, 'is_public' => true, 'starts_at' => now()->subDay()->toDateString(), 'ends_at' => now()->addMonths(3)->toDateString()]);
                }

                continue;
            }

            $brandModel = $offer['brandSlug'] === null ? null : $brand($offer['brandSlug']);

            $promotion = Promotion::query()->create([
                'name' => $offer['name'], 'slug' => $offer['slug'], 'code' => $offer['code'], 'title' => $offer['title'],
                'summary' => $offer['summary'], 'badge_text' => $offer['badge_text'], 'discount_description' => $offer['discount_description'],
                'type' => $offer['type'], 'value' => $offer['value'],
                'starts_at' => now()->subDay()->toDateString(), 'ends_at' => now()->addMonths(3)->toDateString(),
                'stackable' => false, 'status' => Status::Active, 'is_public' => true,
                'terms' => 'Offer valid on selected tyres while the campaign runs and cannot be combined with other offers.',
            ]);

            if ($brandModel !== null) {
                $promotion->eligibilities()->create(['scope' => PromotionEligibilityScope::Brand, 'scope_id' => (string) $brandModel->id]);
            } else {
                foreach (TyreCategory::cases() as $category) {
                    $promotion->eligibilities()->create(['scope' => PromotionEligibilityScope::Category, 'scope_id' => $category->value]);
                }
            }
        }
    }

    private function seedContent(): void
    {
        foreach ([[ContentPageType::BlogPost, DemoContent::blogPosts()], [ContentPageType::Guide, DemoContent::guides()]] as [$type, $items]) {
            foreach ($items as $item) {
                ContentPage::query()->updateOrCreate(
                    ['type' => $type, 'slug' => $item['slug']],
                    [
                        'title' => $item['title'], 'excerpt' => $item['excerpt'], 'body' => $item['body'], 'category' => $item['category'],
                        'status' => PageStatus::Published, 'published_at' => now()->subMonths($item['months_ago']),
                        'meta_title' => $item['title'], 'meta_description' => $item['excerpt'],
                    ],
                );
            }
        }

        foreach (DemoContent::faqs() as $order => $faq) {
            Faq::query()->updateOrCreate(
                ['question' => $faq['question'], 'content_page_id' => null],
                ['answer' => $faq['answer'], 'category' => $faq['category'], 'status' => PageStatus::Published, 'sort_order' => 100 + $order],
            );
        }
    }

    private function seedReviews(): void
    {
        foreach (DemoContent::reviews() as $index => $review) {
            $published = now()->subDays(3 + $index * 9);

            Review::query()->updateOrCreate(
                ['source' => ReviewSource::Google, 'external_id' => 'demo-review-'.($index + 1)],
                [
                    'rating' => $review['rating'], 'author_name' => $review['author'], 'author_photo_url' => null, 'body' => $review['body'],
                    'review_url' => null, 'reply_body' => $review['reply'], 'replied_at' => $review['reply'] === null ? null : $published->copy()->addDay(),
                    'location_id' => null, 'is_hidden' => false, 'published_at' => $published, 'cached_at' => now(),
                ],
            );
        }
    }
}
