<?php

namespace Database\Factories;

use App\Enums\Status;
use App\Enums\TyreSidewall;
use App\Models\TyreModel;
use App\Models\TyreVariant;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<TyreVariant>
 */
class TyreVariantFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'tyre_model_id' => TyreModel::factory(),
            'sku' => 'SKU-'.fake()->unique()->numerify('######'),
            // 'slug' intentionally omitted — auto-generated by TyreVariant::booted() on create.
            'width' => fake()->randomElement([185, 195, 205, 215, 225, 235, 245, 265]),
            'profile' => fake()->randomElement([35, 40, 45, 50, 55, 60, 65]),
            'rim_diameter' => fake()->randomElement([15, 16, 17, 18, 19, 20]),
            'load_index' => (string) fake()->numberBetween(88, 108),
            'speed_rating' => fake()->randomElement(['H', 'V', 'W', 'T']),
            'sidewall' => TyreSidewall::Standard,
            'ean' => fake()->unique()->ean13(),
            'weight_kg' => fake()->randomFloat(2, 7, 15),
            'base_price' => fake()->numberBetween(12000, 45000),
            'status' => Status::Active,
        ];
    }
}
