<?php

namespace Database\Factories;

use App\Enums\Status;
use App\Models\Vehicle;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Vehicle>
 */
class VehicleFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $yearFrom = fake()->numberBetween(2010, 2020);

        return [
            'make' => fake()->randomElement(['Toyota', 'Mazda', 'Holden', 'Ford', 'Hyundai', 'Kia']),
            'model' => fake()->unique()->words(2, true),
            'series' => null,
            'body_type' => fake()->randomElement(['sedan', 'hatch', 'wagon', 'suv']),
            'year_from' => $yearFrom,
            'year_to' => $yearFrom + fake()->numberBetween(2, 6),
            // 'slug' intentionally omitted — auto-generated by Vehicle::booted() on create.
            'status' => Status::Active,
        ];
    }
}
